# Config docs: <https://github.com/alacritty/alacritty/blob/master/alacritty.yml>

window:
  opacity: 0.7
  option_as_alt: Both

shell:
  program: /usr/local/bin/tmux
  args:
    - -l

key_bindings:
  - { key: F, mods: Command|Control, action: ToggleSimpleFullscreen }
  # Send `C-B C-L` instead of `C-L`, which is captured by `vim-tmux-navigator`'s setting.
  - { key: K, mods: Command, chars: "\x02\x0c" }

  # Config for the JIS keyboard.
  - { key: Semicolon, mods: Shift|Command, action: IncreaseFontSize }
  - { key: Yen, chars: \ }
