# Config docs: <https://github.com/alacritty/alacritty/blob/master/alacritty.yml>

font:
  size: 12.0

window:
  opacity: 0.7

shell:
  program: /usr/local/bin/tmux
  args:
    - -l

key_bindings:
  - { key: F, mods: Command|Control, action: ToggleSimpleFullscreen }

  # Config for the JIS keyboard.
  - { key: Semicolon, mods: Shift|Command, action: IncreaseFontSize }
  - { key: Yen, chars: \ }
