[selene]
base = "lua51"

# [selene.structs.Option.append]
# method = true

# [[selene.structs.Option.append.args]]
# type = "any" # TODO: `bool | number | string | table`

[[vim.api.nvim_buf_set_keymap.args]]
type = "number"

[[vim.api.nvim_buf_set_keymap.args]]
type = "string"

[[vim.api.nvim_buf_set_keymap.args]]
type = "string"

[[vim.api.nvim_buf_set_keymap.args]]
type = "string"

[[vim.api.nvim_buf_set_keymap.args]]
type = "table"
required = false

[[vim.api.nvim_get_runtime_file.args]]
type = "string"

[[vim.api.nvim_get_runtime_file.args]]
type = "bool"

[[vim.api.nvim_set_keymap.args]]
type = "string"

[[vim.api.nvim_set_keymap.args]]
type = "string"

[[vim.api.nvim_set_keymap.args]]
type = "string"

[[vim.api.nvim_set_keymap.args]]
type = "table"
required = false

[[vim.call.args]]
type = "string"

[[vim.call.args]]
type = "..."
required = false

[[vim.cmd.args]]
type = "string"

[vim.env."*"]
property = true
writable = "overridden"

[[vim.fn."*".args]]
type = "..."
required = false

[[vim.gsplit.args]]
type = "string"

[[vim.gsplit.args]]
type = "string"

[[vim.gsplit.args]]
type = "bool"

[vim.lsp.protocol.make_client_capabilities]
args = []

[vim.opt."*"]
any = true
# TODO:
# property = true
# struct = "Option"
# writable = "overridden"

[[vim.split.args]]
type = "string"

[[vim.split.args]]
type = "string"

[[vim.split.args]]
type = "table"
required = false
