" Load |defaults.vim| which provides a generally reasonable default setup.
source $VIMRUNTIME/defaults.vim

" Execute only when |+eval| feature is available (|no-eval-feature|).
if 1
  " Revert some settings from |defaults.vim|.
  " I don't like highlighting things inside regular comments.
  unlet c_comment_strings
  " This is not the first time I discovered the command-line window and I know what it is, thanks!
  augroup vimHints
    autocmd!
  augroup END

  source <sfile>:h/init.vim
endif
