" Basic setup for Vim {{{1
" Vim is already older than I am. Why should I care compatibility with even older Vi?
" Also, I don't care about POSIX-compliance of an interactive interface like Vi(m). Indeed,
" compatibility matters for plugins, but few, if any, people writes plugins for (POSIX-)Vi nowadays.
" vint: next-line -ProhibitSetNoCompatible " This is the very first code line of vimrc.
if &compatible | set nocompatible | endif

" Skip loading in tiny and small versions of Vim.
if !1 | finish | endif

" }}}

source <sfile>:h/init.vim

" vim: fdm=marker
