name: Lint

on: [push, pull_request]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lumaxis/shellcheck-problem-matchers@v1
        with:
          format: gcc
      - name: Run ShellCheck
        run: |
          set -o pipefail
          find . -name '*.sh' |
          xargs shellcheck --format gcc --shell=bash \
            config/zsh/{.zprofile,.zshrc} \
            zshenv |
          # Replace the severity so that the problem matcher can understand it.
          # <https://github.com/actions/toolkit/blob/f90a2dc/docs/problem-matchers.md#single-line-matchers>
          sed -E 's/^(.+):([0-9]+): (note|style): (.+)$/\1:\2: \3: \4\n\1:\2: warning: \4/g'
